### ISSUE TITLE
Joining Errors

### ISSUE THREAD

**Issue by peektism** [4meta5/substrate-sauce#9]
First encountered while trying to compile `tax` as per https://github.com/4meta5/substrate-sauce/pull/3#issuecomment-570377579 

Instead of adding another error enum `SuperError`, I'd prefer something more consistent.

## new rule

return either `DispatchError` or `Error<T>`. If there are failure cases involving `DispatchError` in the method, either
1. isolate the logic, extract it into another method, and make the `Error<T>` cases return a `DispatchError` from another method and get processed as such (return type is `DispatchError`
2. OR convert `DispatchError` variants that are exposed in the runtime method to a specific `Error<T>` type so that `Error<T>` can be returned (via explicit `From` implementations)

**Comment by 4meta5** [comment]
Either way, it seems I'll have to implemented `Debug` and `PartialEq` for BadOrigin. This is a very annoying problem to have. Before proceeding, should take a look at the module development in srml and see if they follow informal rules to avoid this problem

**Comment by 4meta5** [comment]
LOL I think I need higher kinded types so that the `Error` variant of the `Result` can just absorb all `DispatchError` and `Error<T>` variants.

**Comment by peektism** [comment]
closed in https://github.com/4meta5/substrate-sauce/pull/3/commits/1cab9f8678eba0cca06e84f7ff99d4d5dffef46e by just adding `.into()` after the error 😑
